import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar"
import Topbar from "@/components/Topbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="h-screen flex flex-col overflow-hidden">
          {/* Topbar (full width) */}
          <Topbar />

          {/* Body below topbar */}
          <div className="flex flex-1 overflow-hidden">
            {/* Sidebar */}
            <aside className="hidden lg:block w-64 flex-shrink-0">
              <Sidebar />
            </aside>

            {/* Main content */}
            <main className="flex-1 overflow-y-auto bg-background p-6 lg:p-8">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
